// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V4
    #ifndef UNIFFI_SHARED_HEADER_V4
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V4
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V4
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️

typedef struct RustBuffer
{
    uint64_t capacity;
    uint64_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H
#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t, int8_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
typedef void (*UniffiForeignFutureFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE
typedef struct UniffiForeignFuture {
    uint64_t handle;
    UniffiForeignFutureFree _Nonnull free;
} UniffiForeignFuture;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
typedef struct UniffiForeignFutureStructU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t, UniffiForeignFutureStructU8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
typedef struct UniffiForeignFutureStructI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t, UniffiForeignFutureStructI8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
typedef struct UniffiForeignFutureStructU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t, UniffiForeignFutureStructU16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
typedef struct UniffiForeignFutureStructI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t, UniffiForeignFutureStructI16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
typedef struct UniffiForeignFutureStructU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t, UniffiForeignFutureStructU32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
typedef struct UniffiForeignFutureStructI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t, UniffiForeignFutureStructI32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
typedef struct UniffiForeignFutureStructU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t, UniffiForeignFutureStructU64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
typedef struct UniffiForeignFutureStructI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t, UniffiForeignFutureStructI64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
typedef struct UniffiForeignFutureStructF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t, UniffiForeignFutureStructF32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
typedef struct UniffiForeignFutureStructF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t, UniffiForeignFutureStructF64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
typedef struct UniffiForeignFutureStructPointer {
    void*_Nonnull returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructPointer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
typedef void (*UniffiForeignFutureCompletePointer)(uint64_t, UniffiForeignFutureStructPointer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
typedef struct UniffiForeignFutureStructRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t, UniffiForeignFutureStructRustBuffer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
typedef struct UniffiForeignFutureStructVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureStructVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t, UniffiForeignFutureStructVoid
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_EVENT_SINK_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_EVENT_SINK_METHOD0
typedef void (*UniffiCallbackInterfaceEventSinkMethod0)(uint64_t, RustBuffer, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_EVENT_SINK
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_EVENT_SINK
typedef struct UniffiVTableCallbackInterfaceEventSink {
    UniffiCallbackInterfaceEventSinkMethod0 _Nonnull onEvent;
    UniffiCallbackInterfaceFree _Nonnull uniffiFree;
} UniffiVTableCallbackInterfaceEventSink;

#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_CLONE_IMAGEJOB
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_CLONE_IMAGEJOB
void*_Nonnull uniffi_reclaim_ffi_fn_clone_imagejob(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_FREE_IMAGEJOB
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_FREE_IMAGEJOB
void uniffi_reclaim_ffi_fn_free_imagejob(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_METHOD_IMAGEJOB_CANCEL
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_METHOD_IMAGEJOB_CANCEL
void uniffi_reclaim_ffi_fn_method_imagejob_cancel(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_METHOD_IMAGEJOB_IS_RUNNING
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_METHOD_IMAGEJOB_IS_RUNNING
int8_t uniffi_reclaim_ffi_fn_method_imagejob_is_running(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_METHOD_IMAGEJOB_WAIT
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_METHOD_IMAGEJOB_WAIT
RustBuffer uniffi_reclaim_ffi_fn_method_imagejob_wait(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_CLONE_SESSION
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_CLONE_SESSION
void*_Nonnull uniffi_reclaim_ffi_fn_clone_session(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_FREE_SESSION
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_FREE_SESSION
void uniffi_reclaim_ffi_fn_free_session(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_METHOD_SESSION_CHECK_DESTINATION
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_METHOD_SESSION_CHECK_DESTINATION
RustBuffer uniffi_reclaim_ffi_fn_method_session_check_destination(void*_Nonnull ptr, RustBuffer dest, uint64_t needed_bytes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_METHOD_SESSION_COUNT
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_METHOD_SESSION_COUNT
uint64_t uniffi_reclaim_ffi_fn_method_session_count(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_METHOD_SESSION_COUNT_MATCHING
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_METHOD_SESSION_COUNT_MATCHING
uint64_t uniffi_reclaim_ffi_fn_method_session_count_matching(void*_Nonnull ptr, RustBuffer filter, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_METHOD_SESSION_DIR
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_METHOD_SESSION_DIR
RustBuffer uniffi_reclaim_ffi_fn_method_session_dir(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_METHOD_SESSION_EXTRACT_TEMP
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_METHOD_SESSION_EXTRACT_TEMP
RustBuffer uniffi_reclaim_ffi_fn_method_session_extract_temp(void*_Nonnull ptr, RustBuffer id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_METHOD_SESSION_FAMILY_COUNTS
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_METHOD_SESSION_FAMILY_COUNTS
RustBuffer uniffi_reclaim_ffi_fn_method_session_family_counts(void*_Nonnull ptr, int8_t deleted_only, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_METHOD_SESSION_GET
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_METHOD_SESSION_GET
RustBuffer uniffi_reclaim_ffi_fn_method_session_get(void*_Nonnull ptr, RustBuffer id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_METHOD_SESSION_IS_SCANNING
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_METHOD_SESSION_IS_SCANNING
int8_t uniffi_reclaim_ffi_fn_method_session_is_scanning(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_METHOD_SESSION_PAUSE
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_METHOD_SESSION_PAUSE
void uniffi_reclaim_ffi_fn_method_session_pause(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_METHOD_SESSION_PREVIEW
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_METHOD_SESSION_PREVIEW
RustBuffer uniffi_reclaim_ffi_fn_method_session_preview(void*_Nonnull ptr, RustBuffer id, RustBuffer kind, uint32_t max_px, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_METHOD_SESSION_QUERY
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_METHOD_SESSION_QUERY
RustBuffer uniffi_reclaim_ffi_fn_method_session_query(void*_Nonnull ptr, RustBuffer filter, uint32_t offset, uint32_t limit, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_METHOD_SESSION_RECOVER
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_METHOD_SESSION_RECOVER
RustBuffer uniffi_reclaim_ffi_fn_method_session_recover(void*_Nonnull ptr, RustBuffer ids, RustBuffer opts, uint64_t sink, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_METHOD_SESSION_REPORT
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_METHOD_SESSION_REPORT
RustBuffer uniffi_reclaim_ffi_fn_method_session_report(void*_Nonnull ptr, RustBuffer format, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_METHOD_SESSION_RESUME_SCAN
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_METHOD_SESSION_RESUME_SCAN
void uniffi_reclaim_ffi_fn_method_session_resume_scan(void*_Nonnull ptr, RustBuffer opts, uint64_t sink, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_METHOD_SESSION_SOURCE_ID
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_METHOD_SESSION_SOURCE_ID
RustBuffer uniffi_reclaim_ffi_fn_method_session_source_id(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_METHOD_SESSION_STOP
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_METHOD_SESSION_STOP
void uniffi_reclaim_ffi_fn_method_session_stop(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_METHOD_SESSION_WAIT
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_METHOD_SESSION_WAIT
RustBuffer uniffi_reclaim_ffi_fn_method_session_wait(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_INIT_CALLBACK_VTABLE_EVENTSINK
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_INIT_CALLBACK_VTABLE_EVENTSINK
void uniffi_reclaim_ffi_fn_init_callback_vtable_eventsink(const UniffiVTableCallbackInterfaceEventSink* _Nonnull vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_FUNC_LIST_SOURCES
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_FUNC_LIST_SOURCES
RustBuffer uniffi_reclaim_ffi_fn_func_list_sources(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_FUNC_OPEN_SESSION
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_FUNC_OPEN_SESSION
void*_Nonnull uniffi_reclaim_ffi_fn_func_open_session(RustBuffer dir, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_FUNC_PROBE
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_FUNC_PROBE
RustBuffer uniffi_reclaim_ffi_fn_func_probe(RustBuffer source, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_FUNC_SNAPSHOT_DIFF
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_FUNC_SNAPSHOT_DIFF
RustBuffer uniffi_reclaim_ffi_fn_func_snapshot_diff(RustBuffer source, uint64_t from_xid, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_FUNC_SNAPSHOTS
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_FUNC_SNAPSHOTS
RustBuffer uniffi_reclaim_ffi_fn_func_snapshots(RustBuffer source, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_FUNC_START_IMAGE
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_FUNC_START_IMAGE
void*_Nonnull uniffi_reclaim_ffi_fn_func_start_image(RustBuffer source, RustBuffer dest, RustBuffer opts, uint64_t sink, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_FUNC_START_SCAN
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_FUNC_START_SCAN
void*_Nonnull uniffi_reclaim_ffi_fn_func_start_scan(RustBuffer source, RustBuffer session_dir, RustBuffer opts, uint64_t sink, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_FUNC_VERSION
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_FUNC_VERSION
RustBuffer uniffi_reclaim_ffi_fn_func_version(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_FUNC_VOLUMES
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_FN_FUNC_VOLUMES
RustBuffer uniffi_reclaim_ffi_fn_func_volumes(RustBuffer source, RustBuffer session_dir, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUSTBUFFER_ALLOC
RustBuffer ffi_reclaim_ffi_rustbuffer_alloc(uint64_t size, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_reclaim_ffi_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUSTBUFFER_FREE
void ffi_reclaim_ffi_rustbuffer_free(RustBuffer buf, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUSTBUFFER_RESERVE
RustBuffer ffi_reclaim_ffi_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_POLL_U8
void ffi_reclaim_ffi_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_CANCEL_U8
void ffi_reclaim_ffi_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_FREE_U8
void ffi_reclaim_ffi_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_reclaim_ffi_rust_future_complete_u8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_POLL_I8
void ffi_reclaim_ffi_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_CANCEL_I8
void ffi_reclaim_ffi_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_FREE_I8
void ffi_reclaim_ffi_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_COMPLETE_I8
int8_t ffi_reclaim_ffi_rust_future_complete_i8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_POLL_U16
void ffi_reclaim_ffi_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_CANCEL_U16
void ffi_reclaim_ffi_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_FREE_U16
void ffi_reclaim_ffi_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_reclaim_ffi_rust_future_complete_u16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_POLL_I16
void ffi_reclaim_ffi_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_CANCEL_I16
void ffi_reclaim_ffi_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_FREE_I16
void ffi_reclaim_ffi_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_COMPLETE_I16
int16_t ffi_reclaim_ffi_rust_future_complete_i16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_POLL_U32
void ffi_reclaim_ffi_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_CANCEL_U32
void ffi_reclaim_ffi_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_FREE_U32
void ffi_reclaim_ffi_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_reclaim_ffi_rust_future_complete_u32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_POLL_I32
void ffi_reclaim_ffi_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_CANCEL_I32
void ffi_reclaim_ffi_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_FREE_I32
void ffi_reclaim_ffi_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_COMPLETE_I32
int32_t ffi_reclaim_ffi_rust_future_complete_i32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_POLL_U64
void ffi_reclaim_ffi_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_CANCEL_U64
void ffi_reclaim_ffi_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_FREE_U64
void ffi_reclaim_ffi_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_reclaim_ffi_rust_future_complete_u64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_POLL_I64
void ffi_reclaim_ffi_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_CANCEL_I64
void ffi_reclaim_ffi_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_FREE_I64
void ffi_reclaim_ffi_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_COMPLETE_I64
int64_t ffi_reclaim_ffi_rust_future_complete_i64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_POLL_F32
void ffi_reclaim_ffi_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_CANCEL_F32
void ffi_reclaim_ffi_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_FREE_F32
void ffi_reclaim_ffi_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_COMPLETE_F32
float ffi_reclaim_ffi_rust_future_complete_f32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_POLL_F64
void ffi_reclaim_ffi_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_CANCEL_F64
void ffi_reclaim_ffi_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_FREE_F64
void ffi_reclaim_ffi_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_COMPLETE_F64
double ffi_reclaim_ffi_rust_future_complete_f64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_POLL_POINTER
#define UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_POLL_POINTER
void ffi_reclaim_ffi_rust_future_poll_pointer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_CANCEL_POINTER
#define UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_CANCEL_POINTER
void ffi_reclaim_ffi_rust_future_cancel_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_FREE_POINTER
#define UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_FREE_POINTER
void ffi_reclaim_ffi_rust_future_free_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_COMPLETE_POINTER
void*_Nonnull ffi_reclaim_ffi_rust_future_complete_pointer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_reclaim_ffi_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_reclaim_ffi_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_reclaim_ffi_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_reclaim_ffi_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_POLL_VOID
void ffi_reclaim_ffi_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_CANCEL_VOID
void ffi_reclaim_ffi_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_FREE_VOID
void ffi_reclaim_ffi_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_RECLAIM_FFI_RUST_FUTURE_COMPLETE_VOID
void ffi_reclaim_ffi_rust_future_complete_void(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_CHECKSUM_FUNC_LIST_SOURCES
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_CHECKSUM_FUNC_LIST_SOURCES
uint16_t uniffi_reclaim_ffi_checksum_func_list_sources(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_CHECKSUM_FUNC_OPEN_SESSION
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_CHECKSUM_FUNC_OPEN_SESSION
uint16_t uniffi_reclaim_ffi_checksum_func_open_session(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_CHECKSUM_FUNC_PROBE
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_CHECKSUM_FUNC_PROBE
uint16_t uniffi_reclaim_ffi_checksum_func_probe(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_CHECKSUM_FUNC_SNAPSHOT_DIFF
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_CHECKSUM_FUNC_SNAPSHOT_DIFF
uint16_t uniffi_reclaim_ffi_checksum_func_snapshot_diff(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_CHECKSUM_FUNC_SNAPSHOTS
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_CHECKSUM_FUNC_SNAPSHOTS
uint16_t uniffi_reclaim_ffi_checksum_func_snapshots(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_CHECKSUM_FUNC_START_IMAGE
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_CHECKSUM_FUNC_START_IMAGE
uint16_t uniffi_reclaim_ffi_checksum_func_start_image(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_CHECKSUM_FUNC_START_SCAN
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_CHECKSUM_FUNC_START_SCAN
uint16_t uniffi_reclaim_ffi_checksum_func_start_scan(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_CHECKSUM_FUNC_VERSION
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_CHECKSUM_FUNC_VERSION
uint16_t uniffi_reclaim_ffi_checksum_func_version(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_CHECKSUM_FUNC_VOLUMES
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_CHECKSUM_FUNC_VOLUMES
uint16_t uniffi_reclaim_ffi_checksum_func_volumes(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_CHECKSUM_METHOD_IMAGEJOB_CANCEL
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_CHECKSUM_METHOD_IMAGEJOB_CANCEL
uint16_t uniffi_reclaim_ffi_checksum_method_imagejob_cancel(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_CHECKSUM_METHOD_IMAGEJOB_IS_RUNNING
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_CHECKSUM_METHOD_IMAGEJOB_IS_RUNNING
uint16_t uniffi_reclaim_ffi_checksum_method_imagejob_is_running(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_CHECKSUM_METHOD_IMAGEJOB_WAIT
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_CHECKSUM_METHOD_IMAGEJOB_WAIT
uint16_t uniffi_reclaim_ffi_checksum_method_imagejob_wait(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_CHECKSUM_METHOD_SESSION_CHECK_DESTINATION
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_CHECKSUM_METHOD_SESSION_CHECK_DESTINATION
uint16_t uniffi_reclaim_ffi_checksum_method_session_check_destination(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_CHECKSUM_METHOD_SESSION_COUNT
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_CHECKSUM_METHOD_SESSION_COUNT
uint16_t uniffi_reclaim_ffi_checksum_method_session_count(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_CHECKSUM_METHOD_SESSION_COUNT_MATCHING
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_CHECKSUM_METHOD_SESSION_COUNT_MATCHING
uint16_t uniffi_reclaim_ffi_checksum_method_session_count_matching(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_CHECKSUM_METHOD_SESSION_DIR
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_CHECKSUM_METHOD_SESSION_DIR
uint16_t uniffi_reclaim_ffi_checksum_method_session_dir(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_CHECKSUM_METHOD_SESSION_EXTRACT_TEMP
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_CHECKSUM_METHOD_SESSION_EXTRACT_TEMP
uint16_t uniffi_reclaim_ffi_checksum_method_session_extract_temp(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_CHECKSUM_METHOD_SESSION_FAMILY_COUNTS
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_CHECKSUM_METHOD_SESSION_FAMILY_COUNTS
uint16_t uniffi_reclaim_ffi_checksum_method_session_family_counts(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_CHECKSUM_METHOD_SESSION_GET
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_CHECKSUM_METHOD_SESSION_GET
uint16_t uniffi_reclaim_ffi_checksum_method_session_get(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_CHECKSUM_METHOD_SESSION_IS_SCANNING
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_CHECKSUM_METHOD_SESSION_IS_SCANNING
uint16_t uniffi_reclaim_ffi_checksum_method_session_is_scanning(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_CHECKSUM_METHOD_SESSION_PAUSE
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_CHECKSUM_METHOD_SESSION_PAUSE
uint16_t uniffi_reclaim_ffi_checksum_method_session_pause(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_CHECKSUM_METHOD_SESSION_PREVIEW
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_CHECKSUM_METHOD_SESSION_PREVIEW
uint16_t uniffi_reclaim_ffi_checksum_method_session_preview(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_CHECKSUM_METHOD_SESSION_QUERY
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_CHECKSUM_METHOD_SESSION_QUERY
uint16_t uniffi_reclaim_ffi_checksum_method_session_query(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_CHECKSUM_METHOD_SESSION_RECOVER
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_CHECKSUM_METHOD_SESSION_RECOVER
uint16_t uniffi_reclaim_ffi_checksum_method_session_recover(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_CHECKSUM_METHOD_SESSION_REPORT
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_CHECKSUM_METHOD_SESSION_REPORT
uint16_t uniffi_reclaim_ffi_checksum_method_session_report(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_CHECKSUM_METHOD_SESSION_RESUME_SCAN
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_CHECKSUM_METHOD_SESSION_RESUME_SCAN
uint16_t uniffi_reclaim_ffi_checksum_method_session_resume_scan(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_CHECKSUM_METHOD_SESSION_SOURCE_ID
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_CHECKSUM_METHOD_SESSION_SOURCE_ID
uint16_t uniffi_reclaim_ffi_checksum_method_session_source_id(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_CHECKSUM_METHOD_SESSION_STOP
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_CHECKSUM_METHOD_SESSION_STOP
uint16_t uniffi_reclaim_ffi_checksum_method_session_stop(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_CHECKSUM_METHOD_SESSION_WAIT
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_CHECKSUM_METHOD_SESSION_WAIT
uint16_t uniffi_reclaim_ffi_checksum_method_session_wait(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_CHECKSUM_METHOD_EVENTSINK_ON_EVENT
#define UNIFFI_FFIDEF_UNIFFI_RECLAIM_FFI_CHECKSUM_METHOD_EVENTSINK_ON_EVENT
uint16_t uniffi_reclaim_ffi_checksum_method_eventsink_on_event(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RECLAIM_FFI_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_RECLAIM_FFI_UNIFFI_CONTRACT_VERSION
uint32_t ffi_reclaim_ffi_uniffi_contract_version(void
    
);
#endif

